version: '3.9'
services:
  database:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_DATABASE: 'dev_cookhome'   
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: '1234'      
      MYSQL_ROOT_PASSWORD: '1234'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - './.mysql-data/db:/var/lib/mysql'