version: '3.9'
services:
  database:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_DATABASE: 'dev_cookhome'   
      MYSQL_ROOT_PASSWORD: '1234'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - './.mysql-data/db:/var/lib/mysql'
      - "./scripts/group.sql:/docker-entrypoint-initdb.d/1.sql"
      - "./scripts/type.sql:/docker-entrypoint-initdb.d/2.sql"
      